# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'torocco_V0.ui'
#
# Created: Thu Dec 28 01:52:34 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.resize(737, 489)
        self.btnSave = QtGui.QPushButton(GUI)
        self.btnSave.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.label = QtGui.QLabel(GUI)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnCom = QtGui.QPushButton(GUI)
        self.btnCom.setGeometry(QtCore.QRect(170, 40, 91, 23))
        self.btnCom.setObjectName("btnCom")
        self.label_3 = QtGui.QLabel(GUI)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtGui.QLabel(GUI)
        self.label_10.setGeometry(QtCore.QRect(430, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btnRestar = QtGui.QPushButton(GUI)
        self.btnRestar.setGeometry(QtCore.QRect(20, 420, 75, 23))
        self.btnRestar.setObjectName("btnRestar")
        self.label_9 = QtGui.QLabel(GUI)
        self.label_9.setGeometry(QtCore.QRect(290, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_2 = QtGui.QLabel(GUI)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnStepUp = QtGui.QPushButton(GUI)
        self.btnStepUp.setGeometry(QtCore.QRect(170, 330, 75, 23))
        self.btnStepUp.setObjectName("btnStepUp")
        self.groupBox_2 = QtGui.QGroupBox(GUI)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 251, 21))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtGui.QLabel(GUI)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 46, 13))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtGui.QLabel(GUI)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtGui.QLabel(GUI)
        self.label_11.setGeometry(QtCore.QRect(600, 20, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btnGraph = QtGui.QPushButton(GUI)
        self.btnGraph.setGeometry(QtCore.QRect(190, 180, 75, 23))
        self.btnGraph.setObjectName("btnGraph")
        self.label_6 = QtGui.QLabel(GUI)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btnStepDown = QtGui.QPushButton(GUI)
        self.btnStepDown.setGeometry(QtCore.QRect(170, 360, 75, 23))
        self.btnStepDown.setObjectName("btnStepDown")
        self.label_7 = QtGui.QLabel(GUI)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBoxStep = QtGui.QComboBox(GUI)
        self.comboBoxStep.setGeometry(QtCore.QRect(20, 350, 69, 22))
        self.comboBoxStep.setObjectName("comboBoxStep")
        self.comboBoxStep.addItem("")
        self.comboBoxStep.addItem("")
        self.comboBoxStep.addItem("")
        self.comboBoxStep.addItem("")
        self.graphicsView = QtGui.QGraphicsView(GUI)
        self.graphicsView.setGeometry(QtCore.QRect(280, 100, 411, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.radioButtonR = QtGui.QRadioButton(GUI)
        self.radioButtonR.setGeometry(QtCore.QRect(20, 280, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonR.setFont(font)
        self.radioButtonR.setMouseTracking(True)
        self.radioButtonR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButtonR.setAutoFillBackground(False)
        self.radioButtonR.setChecked(False)
        self.radioButtonR.setObjectName("radioButtonR")
        self.groupBox = QtGui.QGroupBox(GUI)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 261, 16))
        self.groupBox.setObjectName("groupBox")
        self.btnLoad = QtGui.QPushButton(GUI)
        self.btnLoad.setGeometry(QtCore.QRect(190, 120, 75, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.textEditCom = QtGui.QLineEdit(GUI)
        self.textEditCom.setGeometry(QtCore.QRect(100, 40, 61, 20))
        self.textEditCom.setObjectName("textEditCom")
        self.textEditP = QtGui.QLineEdit(GUI)
        self.textEditP.setGeometry(QtCore.QRect(120, 120, 61, 20))
        self.textEditP.setObjectName("textEditP")
        self.textEditI = QtGui.QLineEdit(GUI)
        self.textEditI.setGeometry(QtCore.QRect(120, 150, 61, 20))
        self.textEditI.setObjectName("textEditI")
        self.textEditD = QtGui.QLineEdit(GUI)
        self.textEditD.setGeometry(QtCore.QRect(120, 180, 61, 20))
        self.textEditD.setObjectName("textEditD")
        self.textEditC = QtGui.QLineEdit(GUI)
        self.textEditC.setGeometry(QtCore.QRect(120, 210, 61, 20))
        self.textEditC.setObjectName("textEditC")
        self.textEditF = QtGui.QLineEdit(GUI)
        self.textEditF.setGeometry(QtCore.QRect(120, 240, 61, 20))
        self.textEditF.setObjectName("textEditF")
        self.textEditPM = QtGui.QLineEdit(GUI)
        self.textEditPM.setGeometry(QtCore.QRect(290, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.textEditPM.setFont(font)
        self.textEditPM.setObjectName("textEditPM")
        self.textEditPC = QtGui.QLineEdit(GUI)
        self.textEditPC.setGeometry(QtCore.QRect(440, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.textEditPC.setFont(font)
        self.textEditPC.setObjectName("textEditPC")
        self.textEditErr = QtGui.QLineEdit(GUI)
        self.textEditErr.setGeometry(QtCore.QRect(590, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.textEditErr.setFont(font)
        self.textEditErr.setObjectName("textEditErr")
        self.btnClose = QtGui.QPushButton(GUI)
        self.btnClose.setGeometry(QtCore.QRect(600, 420, 75, 23))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        GUI.setWindowTitle(QtGui.QApplication.translate("GUI", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("GUI", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GUI", "Port COM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCom.setText(QtGui.QApplication.translate("GUI", "Connetc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GUI", "Derivative ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("GUI", "Position commanded", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRestar.setText(QtGui.QApplication.translate("GUI", "Restar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GUI", "Position machine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GUI", "Integral ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStepUp.setText(QtGui.QApplication.translate("GUI", "Step Up", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GUI", "configuation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GUI", "Steps per", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GUI", "Current limit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GUI", "error ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGraph.setText(QtGui.QApplication.translate("GUI", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GUI", "Proportional ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStepDown.setText(QtGui.QApplication.translate("GUI", "Step Down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GUI", "Max. Error", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStep.setItemText(0, QtGui.QApplication.translate("GUI", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStep.setItemText(1, QtGui.QApplication.translate("GUI", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStep.setItemText(2, QtGui.QApplication.translate("GUI", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStep.setItemText(3, QtGui.QApplication.translate("GUI", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonR.setText(QtGui.QApplication.translate("GUI", "Invert direction", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GUI", "Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("GUI", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditPM.setText(QtGui.QApplication.translate("GUI", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditPC.setText(QtGui.QApplication.translate("GUI", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditErr.setText(QtGui.QApplication.translate("GUI", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("GUI", "Close", None, QtGui.QApplication.UnicodeUTF8))

